<?php
/* 
    i. array()
    ii. is_array()
    iii. in_array()
    iv. array_merge()
    v. array_keys()
    vi. array_key_exists()
    vii. array_shift()
    viii. array_unshift()
    ix. array_push()
    x. array_pop()
    xi. array_values()
    xii. array_map()
    xiii. array_unique()
    xiv. array_slice()
    xv. array_diff()
    xvi. array_search()
    xvii.array_reverse()
*/
